---
- name: "install mysql"
  apt: name={{ item }} state=present
  with_items: mysql_apt_packages

- name: "copy my.cnf"
  copy: src=my.cnf dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: start mysql service
  service: name=mysql state=started enabled=true

- name: "allow remote root login"
  mysql_user: name=root password= priv=*.*:ALL,GRANT host='%'
  notify:
  - restart mysql

- name: create site database
  mysql_db: name={{ item.shortname }} state=present collation=utf8_general_ci
  with_items: sites
  when: sites is defined

- name: create database user
  mysql_user: name={{ item.shortname }} password= priv={{ item.shortname }}.*:ALL host=% state=present
  with_items: sites
  when: sites is defined
