---
# Note
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include Distribution-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Ensure Apache is installed (RedHat).
  yum: >
    name={{ item }}
    state=installed
    enablerepo=""
  with_items: apache_packages

- name: Configure Apache (RedHat).
  lineinfile: >
    dest={{ apache_server_root }}/conf/{{ apache_daemon }}.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }
  - {
    regexp: "^NameVirtualHost ",
    line: "NameVirtualHost *:{{ apache_listen_port }}"
  }
  notify: restart apache

# TODO consider a better way to do this. For now, this accommodates both a
#   Vagrant config file, or a server string passing a single instance of the
#   same variables. See ushedev.nbcuext.com in hosts file for an example.
- name: Define sites if extra vars are passed for a single site
  set_fact:
    sites:
    - subscription: "{{ subscription }}"
      shortname: "{{ shortname }}"
      vhost:
        servername: "{{ servername }}"
        documentroot: "{{ documentroot }}"
  when: sites is not defined and subscription is defined

- name: Add apache vhosts configuration.
  template: >
    src=vhosts.conf.j2
    dest={{ apache_conf_path }}/vhosts.conf
    owner=root group=root mode=644
  notify: restart apache
  when: sites is defined

- name: "create pubstack directory"
  file: path=/var/www/pubstack state=directory

- name: "copy index.php"
  template: src=index.php.j2 dest=/var/www/pubstack/index.php

# We can not do this here as CentOS is not as forgiving as Ubuntu.
# TODO Fix "Invalid command 'MaxProcessCount', perhaps misspelled or defined by
#   a module not included in the server configuration"
# TODO Fix "bad user name nbcuqa3"
#- name: "copy Apache2 conf"
#  copy: src={{ item }} dest={{ apache_conf_path }}
#  with_fileglob:
#    - "conf-available/*"

- name: "start apache"
  service: >
    name={{ apache_daemon }}
    state=started
    enabled=yes

- name: Add hosts entry for each site.
  lineinfile:
    dest=/etc/hosts
    line="127.0.0.1  {{ item.vhost.servername }}"
    insertafter=EOF
  with_items: sites
  when: sites is defined
