---
- hosts: all
  sudo: yes
  roles:
  - common
  - apache
  - mysql
  - php
  - php-mysql
  - php-pear
  - php-xhprof
  - composer
  - drush
  - memcached
  - drupal
  # TODO Move to separate 'vagrant' playbook.
#  - php-xdebug
#  - nfs
#  - splunk
