---
- name: "install apache"
  apt: name=apache2 state=present
  sudo: yes

- name: "install fastcgi module for apache"
  apt: name=libapache2-mod-fastcgi state=present
  sudo: yes

- name: "add vhosts"
  template: >
    src=virtualhost.j2
    dest=/etc/apache2/sites-available/{{ item.shortname }}.conf
    owner=root group=root mode=644
  with_items: sites
  when: sites is defined
  register: vhosts_conf
  notify: restart webserver
  sudo: yes

- name: "enable vhosts"
  shell: a2ensite {{ item.shortname }}.conf
  with_items: sites
  when: vhosts_conf|changed
  notify: restart webserver
  sudo: yes

- name: "create pubstack directory"
  file: path=/var/www/pubstack state=directory

- name: "copy index.php"
  copy: src=index.php dest=/var/www/pubstack/index.php

- name: "copy default vhost"
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf

- name: "copy Apache2 conf"
  copy: src={{ item }} dest=/etc/apache2/conf-available
  with_fileglob:
    - "conf-available/*"

- name: "Enable Required Apache module"
  shell: a2enmod actions fastcgi alias headers rewrite
  register: a2enmod_result
  changed_when: "'already enabled' not in a2enmod_result.stdout"

- name: "Enable Required Apache configs"
  shell: a2enconf php5-fpm
  register: a2enconf_result
  changed_when: "'already enabled' not in a2enconf_result.stdout"

- name: "start apache"
  service: >
    name=apache2
    state=started
    enabled=yes
