---
- name: "install apache"
  apt: name=apache2 state=present
  sudo: yes

- name: "install fastcgi module for apache"
  apt: name=libapache2-mod-fastcgi state=present
  sudo: yes

- name: "create site directory"
  shell: >
      mkdir --parents /var/www/html/{{ item.shortname }}/docroot
      creates=/var/www/html/{{ item.shortname }}/docroot
  with_items: sites
  when: sites is defined
  sudo: yes

- name: "add vhosts"
  template: >
    src=virtualhost.j2
    dest=/etc/apache2/sites-available/{{ item.shortname }}.conf
    owner=root group=root mode=644
  with_items: sites
  when: sites is defined
  notify: restart webserver
  sudo: yes

- name: "enable vhosts"
  shell: a2ensite {{ item.shortname }}.conf
  with_items: sites
  when: sites is defined
  notify: restart webserver
  sudo: yes

- name: "create pubstack directory"
  file: path=/var/www/pubstack state=directory
  register: pubstack_directory_exists

- name: "copy index.php"
  copy: src=index.php dest=/var/www/pubstack/index.php
  when: pubstack_directory_exists !=0

- name: "copy Apache2 conf"
  copy: src={{ item }} dest=/etc/apache2/conf-available
  with_fileglob:
    - "conf-available/*"

- name: "Enable Required Apache module"
  shell: a2enmod actions fastcgi alias headers

- name: "Enable Required Apache configs"
  shell: a2enconf php5-fpm

- name: "start apache"
  service: >
    name=apache2
    state=started
    enabled=yes
