---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure packages are present (RedHat).
  yum: >
    name={{ item }}
    state=present
    enablerepo={{ xhprof_enablerepo }}
  with_items: xhprof_packages
  when: ansible_os_family == 'RedHat'

- name: Install xhprof
  command: pecl install xhprof-{{ xhprof_version }}
  register: xhprof_result
  changed_when: "'already installed' not in xhprof_result.stdout"
  failed_when: "xhprof_result.stderr"

- name: Add to ini.
  ini_file:
    dest: "{{ php_conf_path }}/php.ini"
    section: xhprof
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - option: extension
      value: xhprof.so
    - option: xhprof.output_dir
      value: '"/tmp/xhprof"'

- name: "Setup xhprof tmp directory"
  file: path=/tmp/xhprof mode=0777 state=directory
  notify: restart apache
