---
- name: "install common packages"
  yum: pkg={{ item }} state=present
  with_items: common_packages

- name: Copy host.conf so curl can resolve host names
  copy: src=host.conf dest=/etc/host.conf
