---
- hosts: all
  sudo: yes
  roles:
  - common
  - apache
  - mysql
  - php
  - php-mysql
  - php-pear
#  - php-xdebug
  - php-xhprof
  - composer
  - drush
  - memcached
#  - nfs
  - drupal
#  - splunk
  handlers:
  - name: "restart webserver"
    service: name=apache2 state=restarted
