---
- name: Clone Drush from GitHub.
  git: >
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush_install_path }}
    version={{ drush_version }}
    update={{ drush_keep_updated }}

- name: Install Drush dependencies with Composer.
  shell: >
    {{ composer_path }} install --prefer-source --no-interaction
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php

- name: Create drush symlink.
  file: >
    src={{ drush_install_path }}/drush
    dest={{ drush_path }}
    state=link

- name: Run drush to finish setting it up.
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
  tags: drush

- name: "copy drush file for bash alias and autocompletion"
  shell: cp {{ drush_install_path }}/examples/example.bashrc /home/vagrant/.drush_bashrc
  args:
    creates: /home/vagrant/.drush_bashrc
  tags: drush

- name: "include drush in bash profile"
  lineinfile:
    dest=/home/vagrant/.profile
    regexp="^.*drush_bashrc"
    line="if [ -f ~/.drush_bashrc ] ; then . ~/.drush_bashrc ; fi"
    state=present
  tags: drush
