---
- name: Clone Drush from GitHub.
  git: >
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush_install_path }}
    version={{ drush_version }}
    update={{ drush_keep_updated }}

- name: Install Drush dependencies with Composer.
  shell: >
    {{ composer_path }} install --prefer-source --no-interaction
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php

- name: Create drush symlink.
  file: >
    src={{ drush_install_path }}/drush
    dest={{ drush_path }}
    state=link

- name: Run drush to finish setting it up.
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"
  tags: drush

# See explanation in /etc/bashrc of global user profile /etc/profile.d scripts
- name: Copy drush bashrc file to global profile for alias and autocompletion
  shell: cp {{ drush_install_path }}/examples/example.bashrc /etc/profile.d/drush_bashrc.sh
  args:
    creates: /etc/profile.d/drush_bashrc.sh
  tags: drush
