---
php_apt_packages:
  - php5
  - php5-apcu
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-gmp
  - php5-imagick
  - php5-imap
  - php5-ldap
  - php5-mcrypt
  - php5-oauth
  - php5-pspell
  - php5-sqlite
  - php5-tidy

